### PR TITLE
Confocal options to store/restore a reference scan

### PR DESCRIPTION
**Pull request by marcocapelli**
## Description
3 new buttons are added to the confocal GUI. These buttons (store/restore/clear) allow saving the current scan (store) so it can be easily accessed at a later stage (restore). 

## Motivation and Context
This feature is particularly useful if one wants to zoom in and take high-res scans of multiple smaller regions and need to go back to the overall large scan often.

## How Has This Been Tested?
Tested on a Linux machine (Linux Mint 19.3) with the dummy configuration.
Additional testing on a Windows 7 machine with proper NI card-driven piezo stage and APD detector.

## Screenshots (only if appropriate, delete if not):
QuDi_new_buttons

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by lishuo8779** [comment]
Sorry I forgot how to save my unfinished editing before checking to another branch… haven’t tested this branch yet.

**Review by lishuo8779 — COMMENTED** [review]
Testing results:
- The store/restore function works well on Mac.
- After multiple XY scan (usually > 9), if I start to do Z scan then something goes wrong in the "Forward/Back" buttons with the warning showing in attached image. I think it's triggered by the 10 image store limitation in original code:
Screen Shot 2020-04-15 at 9 14 41 pm

Curiosity:
- When saving images from this branch a "Saving..." sign would pop up, but no code changes to view this function. Is it because you built this branch after merged the updates from Ulm Qudi?

**Review by MdevriesPhys — APPROVED** [review]
Worked on Windows 8.1, tried to get it to crash with lots of forwards/backwards/save/restore and seems to be stable

**Comment by marcocapelli** [comment]
> Testing results:
> 
>     * The store/restore function works well on Mac.
> 
>     * After multiple XY scan (usually > 9), if I start to do Z scan then something goes wrong in the "Forward/Back" buttons with the warning showing in attached image. I think it's triggered by the 10 image store limitation in original code:
> 
> 
> Screen Shot 2020-04-15 at 9 14 41 pm
> 
> Curiosity:
> 
>     * When saving images from this branch a "Saving..." sign would pop up, but no code changes to view this function. Is it because you built this branch after merged the updates from Ulm Qudi?

I was not able to reproduce the error. I tried taking 10+ maps switching between xy and depth and saving and restoring and then continuing to take more maps but it always worked fine.

Yes, the pop up is one of the new "functionality" after the merging from Ulm Qudi.

**Pull request merged**
