### PR TITLE
Laser fix

### PR DESCRIPTION
**Pull request by MdevriesPhys**
**Laser module improvements**

- Laser module is now laid out vertically
- Added images to indicate if the laser is on/off (finally).
- Laid groundwork for changing what is plotted (toolbar dropdown, identified what the colours all actually correspond to

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Review by MdevriesPhys — COMMENTED** [review]
The laser config file doesn't actually need to be merged

**Comment by marcocapelli** [comment]
> The laser config file doesn't actually need to be merged

Yeah, the config files are usually local and never pushed except the default one. And also is a .py file and would not work as a config file.

**Comment by marcocapelli** [comment]
A couple of doubts:
- Why there is the entire confocal GUI edited?
- I cannot figure out why but the laser GUI is not rescaling with the window itself.
- The text boxes are also weirdly occupying a lot of empty space.
- I had a play this afternoon and created a couple of fancy shutter icons. Not sure how to show you the result.

**Comment by marcocapelli** [comment]
>     * I had a play this afternoon and created a couple of fancy shutter icons. Not sure how to show you the result.

Got it. I can just push a new commit.

**Comment by MdevriesPhys** [comment]
> * Why there is the entire confocal GUI edited?

Edited the GUI .ui file's format, shouldn't actually change anything on the functionality side of things. It as the only way to follow how it's actually laid out, as it was really badly formatted before. Not at all married to it, but the edit I made is a real improvement to being able to edit other .ui files.

> * I cannot figure out why but the laser GUI is not rescaling with the window itself.

Me neither. I pushed this up because it is functioning now, it's next on my list to fix - I suppose it's a nice new bug to repair.

> * The text boxes are also weirdly occupying a lot of empty space.

Which text boxes? I think this is connected to the "bug" described above.

> * I had a play this afternoon and created a couple of fancy shutter icons. Not sure how to show you the result.

Oh man, that looks sweet as! Nice!!

**Comment by MdevriesPhys** [comment]
> And also is a .py file and would not work as a config file.

I completely missed that! No wonder it wasn't working!

**Review by lishuo8779 — COMMENTED** [review]
Apology for the lagging reply, trying to follow up the github workflow... Comments following:
- The icon space looks great! 
- The selection from Graph menu (Plot temp/current/power) seems not working for my laptop
- Prefer the landscape layout for better using the screen space also enlarging the plotting graph by default

**Comment by MdevriesPhys** [comment]
> The selection from Graph menu (Plot temp/current/power) seems not working for my laptop

Won't work anywhere yet, they're just place keepers at the moment and haven't been implemented.

**Comment by marcocapelli** [comment]
It rescales perfectly on my pc now!

One last thing before sending it to master is to clean up the icon folders (I do not think we have to test on the lab since there are mostly GUI changes). 
I would remove the unused shutter icons (both png and svg) and put the png files, with the correct size, in the 22x22 folder. Also, only the ON/OFF icons should be needed as Qt automatically adds desaturated and grayscale ones when the button is deactivated and so on.

**Review by marcocapelli — APPROVED** [review]

**Review by lishuo8779 — APPROVED** [review]

**Pull request merged**
